spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:C:/Users/user/Desktop/RoyalWebStore/royalwebstore-db'
  jpa:
    hibernate:
      ddl-auto: create-drop
